per_listener_settings true

listener 1883
listener_allow_anonymous true

listener 8883
cafile ca.crt
certfile server.crt
keyfile server.key
listener_allow_anonymous false
require_certificate true
use_identity_as_username true
acl_file acl_file.acl