mqtt:
  host: "10.0.0.14"
  port: 8883
  tls:
    cafile: "ca.crt"
    certfile: "client.crt"
    keyfile: "client.key"
wifi:
  network: "MyWiFiSSID"
  passphrase: "supersecretpassword"
  mode: "dynamic"